spring.application.name=ride-management-service
server.port=${PORT:8083}
server.error.include-message=never
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ridelink_ride_db?connectionTimeZone=UTC}
spring.datasource.username=${DB_USERNAME:ridelink_ride}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.accept-float-as-int=false
ridelink.driver-service-url=${DRIVER_SERVICE_URL:http://localhost:8081}
ridelink.fare-service-url=${FARE_SERVICE_URL:http://localhost:8084}
springdoc.swagger-ui.path=/swagger-ui.html

spring.flyway.locations=classpath:db/migration/{vendor}
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
ridelink.security.jwt-secret=${JWT_SECRET:}
