spring.application.name=fare-payment-service
server.port=${PORT:8084}
server.error.include-message=never

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/fare-payment;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.accept-float-as-int=false

ridelink.security.issuer=${JWT_ISSUER:http://localhost:8081}
ridelink.security.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8081/.well-known/jwks.json}
ridelink.security.audience=${JWT_AUDIENCE:ridelink}
ridelink.ride-service-url=${RIDE_SERVICE_URL:http://localhost:8083}
springdoc.swagger-ui.path=/swagger-ui.html
